services:
  - type: web
    name: rain-check
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENWEATHER_API_KEY
        sync: false
