apiVersion: v1
kind: Secret
metadata:
  name: rain-check-secrets
type: Opaque
stringData:
  # Using stringData allows us to put plain text here (K8s will base64 it)
  # In production, NEVER commit real secrets to Git. Use external secret managers.
  OPENWEATHER_API_KEY: "adea867852ed0e01a32fd37656a2576e" 
  SESSION_SECRET: "antigravity-is-awesome-2004"
